spring:
  datasource:
    url: jdbc:mysql://192.168.126.10:3306/sfg_prod?&useTimezone=true&serverTimezone=UTC
    username: sfg_prod_user
    password: guru
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false

#need to set active profile to prod in run configuration
